version: '3'

services:
  mongodb:
    image: mongo
    restart: always

  main:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:8082
    links:
      - mongodb
    depends_on:
      - mongodb